import type { Metadata } from "next";
import { SITE } from "./site";

type PageMetaInput = {
  title: string;
  description: string;
  path: string; // leading slash, e.g. "/compare-pos-systems"
  type?: "website" | "article";
  /** Optional featured image (leading-slash path), used for OG/Twitter cards. */
  image?: string;
  /** Override the canonical URL (e.g. point a duplicate at its preferred page). */
  canonical?: string;
};

/** Build per-page metadata with canonical + OG/Twitter wired up. */
export function pageMeta({ title, description, path, type = "website", image, canonical }: PageMetaInput): Metadata {
  const url = `${SITE.url}${path}`;
  const canonicalUrl = canonical ?? url;
  // Pages with their own featured image use it; everything else falls back to the
  // branded site OG image (generated by app/opengraph-image.tsx). We reference it
  // explicitly because overriding `openGraph` per page drops the file-based default.
  const ogImage = image ? `${SITE.url}${image}` : `${SITE.url}/opengraph-image`;
  return {
    title,
    description,
    alternates: { canonical: canonicalUrl },
    openGraph: {
      type,
      url,
      title,
      description,
      siteName: SITE.name,
      locale: "en_GB",
      images: [{ url: ogImage, width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      site: SITE.twitter,
      images: [ogImage],
    },
  };
}
